api/account/account.go, chain/cosmos/client.go, chain/cosmos/tx.go, chain/filecoin/account.go, chain/filecoin/filecoin_test.go, chain/terra/terra.go, chain/terra/terra_test.go, infra/.env, infra/docker-compose.yaml, infra/terra/run.sh, multichain_test.go
Previously, the transaction builder would require the user to specify the account number upon instantiating the object. This is obviously an issue if the transaction builder is expected to work for multiple different accounts, as each of them would have a different account number. The transaction builder interface has now been updated to accept a `Client` which can be used to fetch the account number upon building the transaction, rather than upon initialisation of the builder. Additionally, some slightly incorrect logic regarding nonce (sequence number) fetching has been removed.
=> Fix Cosmos transaction builder

chain/bitcoin/bitcoin.go, chain/bitcoin/gas.go, chain/bitcoin/gas_test.go, infra/bitcoin/run.sh, infra/docker-compose.yaml
Estimate network fee to be paid (sats per byte) needed to confirm the transaction within the desired number of blocks.
* RPC call used: `estimatesmartfee`
* Error on HTTP error
* Error on not enough chain history to make an estimate
=> bitcoin fee estimation

.github/workflows/test.yml, api/account/account.go, api/gas/gas.go, chain/bitcoin/gas.go, chain/bitcoin/gas_test.go, chain/cosmos/gas.go, chain/cosmos/tx.go, chain/filecoin/account.go, chain/filecoin/filecoin_test.go, chain/filecoin/gas.go, chain/filecoin/gas_test.go, chain/terra/terra_test.go, multichain_test.go
This PR fixes the erroneous use of gas base, gas price (also known as premium), and gas cap. It standardised how these values are fetched from nodes, how they're returned from the Gas API, and how they're consumed by the Account API when building transactions.
Previously, we were using gas cap as if it was the gas base. In reality, gas base cannot be known (only estimated), so the only values available are gas price (also known as premium) and gas cap. Both of these values are per-gas unit. The Gas API has been standardised to return price and then cap, to return price=cap for chains that do not distinguish between the two, and also updates the Account API to accept gas limit, price, and cap when building transactions.
=> Fix the use of gas price and gas cap

chain/bitcoin/gas.go
The Bitcoin gas estimation currently fails when the `feeRate` returned by the Bitcoin node is less than `1024/1e8`. This is because of the sats/byte calculation which truncates the result of `feeRate * btcToSatoshis / kilobyteToByte` by converting it directly to a `uint64`. In the case the `feeRate` is less than `0.00001024`, the resulting value (less than 1) gets rounded down to `0`, meaning any submission that uses this estimate directly is guaranteed to fail (also in the case that any multipliers are applied).
This PR updates the gas estimator to round up the sats/byte prior to returning the estimates.
=> Round up sats per byte

chain/cosmos/tx.go
Inside the `BuildTx` function for cosmos we encode the payload by calling `payload.String()`, however when decoding we simply convert the `tx.memo` string to `pack.Bytes` directly. This PR updates the encoding to be `string(payload)` so when fetching the payload, the same data is returned.
=> Fix Cosmos payload encoding

api/account/account.go, chain/cosmos/client.go, chain/cosmos/tx.go, chain/filecoin/client.go, chain/terra/terra.go, chain/terra/terra_test.go, multichain_test.go
This PR updates the Filecoin and Terra clients to expose an `AccountBalance` function that returns the balance of a given account. This is currently possible for UTXO-based clients through the `UnspentOutputs` function (for imported addresses), however hasn't been possible for account-based clients until now.
We could also potentially update the account client API to make this a requirement.
EDIT: The `AccountBalance` function has been added to the account client API.
=> Add helper functions for fetching account balances

chain/cosmos/client.go, chain/cosmos/tx.go, chain/terra/terra.go
This PR adds a field `hrp` in `cosmos.Client`. This helps us in potentially supporting multiple cosmos-chains in the future, as we globally set the `prefix` before doing any operation.
=> fix: set prefix in cosmos client

.github/workflows/test.yml, Dockerfile
Create a base docker image for Multichain that can be re-used by any other service that depends on the multichain packages.
DockerHub repo [here](https://hub.docker.com/r/renbot/multichain)
=> Multichain base image

chain/bitcoin/bitcoin.go, chain/bitcoin/gas.go, chain/bitcoin/gas_test.go, chain/bitcoincash/gas.go, chain/bitcoincash/gas_test.go, chain/dogecoin/gas_test.go, chain/zcash/gas.go, chain/zcash/gas_test.go, infra/zcash/Dockerfile, infra/zcash/run.sh, infra/zcash/zcash.conf, multichain_test.go
This PR includes:
* Handle Gas API for BitcoinCash and Zcash differently than Bitcoin/Dogecoin/DigiByte
* Add `EstimateFeeLegacy` that calls the `estimatefee` RPC call instead of `estimatesmartfee`
* Add tests for Gas API for all UTXO chains
* Upgrade Zcash infra [ref](https://forum.zcashcommunity.com/t/end-of-debian-jessie-support-is-on-october-1st-2020/37313) (We can now include Zcash in our Multichain test suite)
The Gas API for UTXO chains will now return `fallbackGas` if there was an error while estimating gas, or invalid fee rates were returned from the node.
=> UTXO Gas Estimation

Dockerfile
This PR creates `multichain` image on top of `golang` instead of `ubuntu:bionic`. This means the overall image is much smaller and takes less time to be built. No change is required in other repositories that rely on `renbot/multichain:latest`.
=> ci: use golang base image instead of ubuntu for smaller image

Dockerfile
Original fix was added here: https://github.com/renproject/lightnode/pull/108
This PR uses the same fix but in multichain so that the dependant images don't need to set it.
=> fix(ci): use proxy to download packages faster

chain/filecoin/client.go
Previously we were just printing the address if the `StateGetActor` call failed. This PR updates the call to return the Filecoin error message as well.
=> Improve Filecoin errors

chain/cosmos/address.go, chain/cosmos/client.go, chain/cosmos/tx.go, chain/terra/address_test.go, chain/terra/terra.go, chain/terra/terra_test.go, multichain_test.go
There are several functions within the Cosmos SDK that make use of a global configuration to fetch the Bech32 prefix for an account. https://github.com/renproject/multichain/pull/49 updated the Multichain to set this prefix before each operation that interacts with the Cosmos SDK to allow us to support multiple Cosmos-compatible chains in the future. This has the obvious downside of potentially causing panics if the functions are called concurrently, and due to this we have decided to move away from this in favour of a config initialisation on boot. The downside to this is we cannot easily add support for other Cosmos-compatible chains in the near future because they will all use different prefixes. However, this issue is being tracked in the Cosmos SDK …
=> Fix Cosmos config initialisation

api/account/account.go, api/utxo/utxo.go, chain/bitcoin/bitcoin.go, chain/cosmos/client.go, chain/filecoin/client.go, infra/bitcoincash/Dockerfile, multichain_test.go
Adds the method:
```go
func (client *Client) LatestBlock(ctx context.Context) (pack.U64, error) 
```
to both the `utxo.Client` as well as `account.Client` interfaces. Tested for:
=> feat: client to expose latest block api

chain/cosmos/client.go
Previously, the context provided to query functions in the Cosmos client was getting ignored in favour of an internal client context. This PR updates these functions to continue looping until the parent context has expired.
=> Use provided contexts for Cosmos chains

.github/workflows/test.yml, chain/zcash/address.go, chain/zcash/address_test.go, chain/zcash/utxo.go
Currently the `AddressEncodeDecoder` for zcash will not return an error when trying to decode an address on different network, for example:
```golang
addrEncodeDecoder := zcash.NewAddressEncodeDecoder(&zcash.MainNetParams)
addr := multichain.Address("t28Tc2BUTHifXthexsohy89umGdqMWLSUqw") // Testnet address 
_, err := addrEncodeDecoder.DecodeAddress(addr)
Expect(err).To(HaveOccurred())
```
I expect this to return an error when trying to decode a testnet address using a mainnet `AddressEncodeDecoder`.
All other bitcoin-like chains are working fine and I expect zcash to have the same behaviour.  
The `param` we passed to initialize the `AddressEncodeDecoder` is not used when encoding/decoding.  And the 
`parsePrefix` function checks all possible networks. I changed that to compare only with …
=> Zcash AddressDecoder

chain/digibyte/digibyte.go
This PR fixes the prefix byte for DigiByte Script Hash Address
1. [DigiByte params](https://github.com/DigiByte-Core/digibyte/blob/82414be2e78bd136daeb91f55c72768a9b700957/src/chainparams.cpp#L233)
A follow up PR will be required to also handle the "Old Prefix" for Script Hash Address.
=> fix: prefix byte for script hash address

multichain.go, multichain_test.go
This PR adds missing declarations, namely, `NativeAsset` and `ChainType` for Solana.
=> fix: add missing declarations for Solana

go.mod
Due to different toolchains (in `filecoin-ffi` and `solana-ffi`) and link time optimisation enabled by default for staticlibs, duplicate symbols were found from both `libfilcrypto.a` and `libsolana_ffi.a`.
The bumped up version of `solana-ffi` resolves this.
=> bump up solana-ffi version

chain/cosmos/address.go, chain/terra/address_test.go
So far we were only relying on the `cosmos-sdk/types` package to catch any possible address-related errors (format, checksum, etc.). But an empty string `multichain.Address("")` passed the decoder giving us no error yet an invalid raw address.
We now explicitly ensure that raw addresses are `AddrLen` long when decoding/encoding.
=> fix: cosmos addrs are expected to be 20-bytes long

infra/bitcoin/Dockerfile
I'm getting an error when compiling the bitcoin local image with `ubuntu:xenial`
```
Step 3/12 : RUN apt-get install --yes curl
---> Running in 650c4a06bf08
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
curl
0 upgraded, 1 newly installed, 0 to remove and 10 not upgraded.
Need to get 139 kB of archives.
After this operation, 340 kB of additional disk space will be used.
Err:1 http://security.ubuntu.com/ubuntu xenial-security/main amd64 curl amd64 7.47.0-1ubuntu2.16
404  Not Found [IP: 91.189.88.152 80]
Err:1 http://security.ubuntu.com/ubuntu xenial-security/main amd64 curl amd64 7.47.0-1ubuntu2.16
404  Not Found [IP: 91.189.88.152 80]
E: Failed to fetch …
```
=> Update base image for bitcoin local infra

.github/workflows/test.yml, chain/solana/solana.go, chain/solana/solana_test.go, chain/solana/solanarpc.go, go.mod, go.sum
This PR implements APIs to get gateway addresses from Ren's [Gateway Registry](https://github.com/renproject/ren-solana/pull/4) on Solana
=> feat: fetch and deserialize gateway registry account data

Dockerfile
- Updated solana-ffi submodule to the lastest commit
- Updated Dockerfile to use the latest solana-ffi commit and updated some steps
This PR fixes the dependency issues in the lightnode build
Signed-off-by: Soumya Ghosh Dastidar <gdsoumya@gmail.com>
=> Updated solana-ffi submodule and Dockerfile

chain/bitcoincash/address.go, chain/bitcoincash/address_test.go
This PR adds a fix for BitcoinCash address encoders-decoders.
The `multichain/chain/bitcoincash` package's `TxBuilder.BuildTx` relies on the method `addressFromRawBytes` that consumes raw bytes and outputs a type that implements the `btcutil.Address` interface.
The previous codebase for `addressFromRawBytes` only accounted for CashAddr format, but did not take into account the case for LegacyAddr.
This PR accounts for legacy addresses. The PR also fixes another issue where `RegressionNetParams` were hard-coded in the `encodeLegacyAddress` method. The legacy address format was not thoroughly tested, and as it seems must have been rarely encountered in RenVM.
=> fix: bitcoincash addressFromRawBytes should account for legacy addr

chain/solana/solana_test.go, chain/solana/solanarpc.go
This PR removes application specific structs that were in Multichain's solana package. Instead they will be moved to Darknode.
=> refactor: application specific structs moved out of multichain

.github/workflows/test.yml, chain/solana/solana.go, chain/solana/solana_test.go, infra/docker-compose.yaml
- Uses `renbot/ren-solana` docker image for the CI
- Fixes tests based on the above change
- Adds `solana` service to the Multichain infra's `docker-compose` file
=> solana infra

.github/workflows/build.yml
This PR triggers a docker build for multichain only when a new tag is created. It uses the tag version to also tag the docker image.
=> feat: trigger docker build on new tag | tag image

chain/ethereum/address.go, multichain.go, multichain_test.go
This PR adds an `AssetType` that differentiates assets on host-chains, by whether they're native assets or tokens deployed on these chains.
=> feat: add asset type

.github/workflows/test.yml, Dockerfile, chain/solana/solana_test.go
- Relevant changes for solana burn log's recipient length extended to 64-bytes
- Update solana-ffi commit
=> Solana recipient len

.github/workflows/test.yml, infra/zcash/run.sh
After zcash v4.5.0, the daemon takes a bit longer to run. Inadequate sleep time means that the subsequent `importaddress` fails, which also then doesn't watch for that address. This in turn results in the `listunspent` RPC call returning an empty list.
=> fix: wait longer for daemon to start

Dockerfile
The CI for building the multichain image fails because of [Deprecation of 'go get' for installing executables](https://go.dev/doc/go-get-install-deprecation)
=> Fix the dockerfile for go1.18

chain/filecoin/client.go
- Limit the tx method to be `Send` for filecoin deposits
=> Check filecoin tx method 

.github/workflows/test.yml, go.mod, multichain.go, multichain_test.go
Add support for non-Ethereum stablecoins such as USDC/USDT on Polygon/Avalanche. This PR also defines some new types for token assets on Goerli.
=> Support for non-Ethereum stablecoins

chain/evm/client.go
We cannot get chain id from tx signed using a homestead signer. (see [EIP-155](https://eips.ethereum.org/EIPS/eip-155))
So we only check the chain id for replay-protected txs.
=> Support homestead signer when validating tx chain ID
